name: Check Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Dependency Review
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
        with:
          fail-on-severity: low

  sonarcloud:
    name: SonarCloud Scan
    needs: dependency-review
    runs-on: ubuntu-22.04
    env:
      UPLOADER_URL: "http://localhost:7337"
      FILE_S3_BUCKET: "apha"
      FILE_S3_PATH: "biosecurity-map"
      CONSUMER_BUCKETS: "apha"
      MOCK_VIRUS_SCAN_ENABLED: false
      AWS_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      GATEWAY_ID: ${{ secrets.GATEWAY_ID }}
      GATEWAY_PASSWORD: ${{ secrets.GATEWAY_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Run template check
        run: ./template-check.sh
        shell: bash

      - name: Test code and Create Test Coverage Reports
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: |
          npm ci
          npm audit --omit=dev
          npm run build
          npm run format:check
          npm run lint
          npm run test -- --projects jest-projects/core.js
          npm run test -- --projects jest-projects/fmd.js
          npm run test -- --projects jest-projects/exotics.js
          npm run test -- --projects jest-projects/tb.js

      - name: SonarCloud Scan
        if: github.actor != 'dependabot[bot]'
        uses: SonarSource/sonarqube-scan-action@713881670b6b3676cda39549040e2d88c70d582e # master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  pr-validator:
    name: Run Journey Tests
    needs: dependency-review
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        test-suite:
          - user-journey-test
          - exotics-journey-test
          - fmd-journey-test
    env:
      UPLOADER_URL: "http://localhost:7337"
      FILE_S3_BUCKET: "apha"
      FILE_S3_PATH: "biosecurity-map"
      CONSUMER_BUCKETS: "apha"
      MOCK_VIRUS_SCAN_ENABLED: false
      AWS_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      GATEWAY_ID: ${{ secrets.GATEWAY_ID }}
      GATEWAY_PASSWORD: ${{ secrets.GATEWAY_PASSWORD }}
      DEFRA_ID_ENABLED: false

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        run: |
          npm ci
          npm audit --omit=dev
          npm run build

      - name: Start docker compose
        env:
          DEFRA_ID_CLIENT_SECRET: ${{ secrets.DEFRA_ID_CLIENT_SECRET }}
          DEFRA_ID_ENABLED: false
        run: docker compose up --wait-timeout 300 -d --quiet-pull

      - name: Run ${{ matrix.test-suite }}
        run: npm run ${{ matrix.test-suite }}

      - name: Upload allure report
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: allure-report-${{ matrix.test-suite }}
          path: ./allure-report

      - name: Upload docker compose logs
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: docker-compose-logs-${{ matrix.test-suite }}
          path: ./logs.txt

      - name: Cleanup
        if: always()
        run: docker compose down
