name: Browserstack extended tests (desktop)

on:
  schedule:
    - cron: '0 1 * * *' # Runs at 1am
  workflow_dispatch:

env:
  AWS_REGION: eu-west-2
  AWS_ACCOUNT_ID: '094954420758'

concurrency:
  group: browserstack-extended-tests-desktop

jobs:
  build:
    name: CDP-build-workflow
    env:
      GATEWAY_ID: ${{ secrets.GATEWAY_ID }}
      GATEWAY_PASSWORD: ${{ secrets.GATEWAY_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Start docker compose
        env:
          GATEWAY_ID: ${{ secrets.GATEWAY_ID }}
          GATEWAY_PASSWORD: ${{ secrets.GATEWAY_PASSWORD }}
          DEFRA_ID_CLIENT_SECRET: ${{ secrets.DEFRA_ID_CLIENT_SECRET }}
          DEFRA_ID_ENABLED: false
          SEND_TO_CASE_MANAGEMENT_ENABLED: false
        run: |
          docker compose up --wait-timeout 300 -d --quiet-pull

      - name: Browserstack tests
        run: |
          npm ci
          npm run user-journey-test:bs-extended-desktop
        env:
          BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
          BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
          DEFRA_ID_ENABLED: false

      - name: debug
        if: always()
        run: |
          docker compose logs > logs.txt
          docker ps
      - name: Upload docker compose logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docker-compose-logs
          path: ./logs.txt

      - name: cleanup
        if: always()
        run: docker compose down
