name: Browserstack extended tests (desktop)

on:
  workflow_run:
    workflows: ['Publish']
    types:
      - completed

env:
  AWS_REGION: eu-west-2
  AWS_ACCOUNT_ID: '094954420758'

concurrency:
  group: browserstack-extended-tests-desktop

jobs:
  checkout:
    name: Check out Code
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

  docker:
    name: Start Docker Compose
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Start docker compose
        env:
          NOTIFY_TEMPLATE_ID: ${{ secrets.NOTIFY_TEMPLATE_ID }}
          NOTIFY_API_KEY: ${{ secrets.NOTIFY_API_KEY }}
          NOTIFY_CASE_DELIVERY_EMAIL_ADDRESS: ${{ secrets.NOTIFY_CASE_DELIVERY_EMAIL_ADDRESS }}
        run: |
          docker compose up --wait-timeout 300 -d --quiet-pull

  browserstack:
    name: Browserstack Extended Tests
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Run Browserstack extended desktop tests
        run: |
          npm ci
          npm run user-journey-test:bs-extended-desktop
        env:
          BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
          BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}

  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    needs: browserstack
    if: always()
    steps:
      - name: Stop Docker Compose
        run: docker compose down

